name: Sync to Hugging Face space
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: huggingface/github-action@v2
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          hf_repo_id: abhishek0164/globevote
          repo_type: space
